-- Estrutura do Banco de Dados para o Futsal da Firma

CREATE TABLE IF NOT EXISTS `jogadores` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `nome` VARCHAR(100) NOT NULL,
  `valor_pago` DECIMAL(10,2) DEFAULT 0.00,
  `criado_em` TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `configuracoes` (
  `chave` VARCHAR(50) PRIMARY KEY,
  `valor` VARCHAR(255) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `pagamentos_quadra` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `descricao` VARCHAR(150) NOT NULL,
  `valor` DECIMAL(10,2) NOT NULL,
  `criado_em` TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
